dataset-api-host: "http://localhost:22000"
import-api-host: "http://localhost:21800"
dev-auth-token: "FD0108EA-825D-411C-9B1D-41EF7727F465"
recipe-id: "b944be78-f56d-409b-9ebd-ab2b77ffe187"
upload-alias-name: "CPI COICOP"
upload-url: "s3://dp-dimension-extractor/EXAMPLE_V4-coicopcomb-inc-geo-code.csv"
website-host: "http://localhost:20000"
mongo-url: localhost:27017
neo4j-url: bolt://localhost:7687